### ISSUE TITLE
getParameter returns a string (always?)

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#15]
https://github.com/gammasim/gammasim-tools/blob/3bf4a7d745056969c2bc1e10b82993bec0ab40c8/simtools/model/telescope_model.py#L320

The getParameter function returns a string when calling

`telModel.getParameter('effective_focal_length')`

Not sure if a string is always returned, but from the few I checked it seems so. In the original yaml DB, values are saved with the "correct" type (for the most part), so I am not sure why this happens. @RaulRPrado, any ideas?

**Comment by RaulRPrado** [comment]
This is a temporary simplification because I didn't have the time to implement a parameter validation properly.

It's not as simple as it may seem. 
Very few parameters are saved as floats and all the rest (including numbers) are saved as strings. But that is not the main problem.

To validate the type we need to have somewhere stored the expected type of the parameters. That is the purpose of the model_parameters module, which is only a template by now, containing only few parameters listed. For the parameters listed there, the function _validateParameter check for the type and convert if possible. You can try getParameter('focal_length') to see it working.

That was my first idea. However, I got myself in trouble when dealing with parameters which cannot be assigned to basic types. For example, focus_offset = 6.55 28 0 0, which is a list of numbers of different types. Or nightsky_background = all:0. 
Dealing with this kind of parameters will be a bit trickier, but it's doable. It's just a matter of dedicating some time to it. 

If you want to help, the simple next thing is to fill in the model_parameters module with the parameters with well defined types, and leave the rest as strings by now. Note that the validation of the parameters would also approach the problem with different names for the same parameter. 

Be aware of https://github.com/gammasim/gammasim-tools/issues/10 though. My plan for the future is actually not use modules for this parameter lists, but yml files.

**Comment by orelgueta** [comment]
What I do is 
`try:`
     `value = float(value)`
`except ValueError:`
    `pass`

It's far from perfect, but it deals with all float like parameters quite well and then it's easier to only deal with the special cases you mentioned. It does turn integers into floats, but at least for my use it is not an issue (and it's easy to fix I guess).
In order to simplify simtools a little for now, I actually implemented that in the writing of the yaml database. So now all values that can be floats, are saved as such and you can read them directly. What do you think?

**Comment by RaulRPrado** [comment]
Not sure about that. Some parameters should always be int.
I think for now we could just try to fill in the parameter list with the ones that are simple float or int. This should be very mechanical job.
For these basic types, the current code is working fine.

Should we create another issue requesting the proper implementation of the parameter validation or should we keep this one open to remind us that this is an important todo item?

**Comment by orelgueta** [comment]
We can keep this one open, but I would still suggest that we only list the ones that should be int. It would be much shorter and easier than listing also the float ones (they are the majority). 

I am actually not yet convinced we have to also list the int ones, which ones **have** to be int?

**Comment by RaulRPrado** [comment]
> We can keep this one open, but I would still suggest that we only list the ones that should be int. It would be much shorter and easier than listing also the float ones (they are the majority).
> 
> I am actually not yet convinced we have to also list the int ones, which ones **have** to be int?

Conceptually, there are many parameters that are integers. Reflecting the conceptual meaning at the implementation is always better than not do it.

The list of model parameters seems a good idea to me, and may be very helpful later. Why not to do it properly since the beggining? Is there some specific parameter that you need now?
We don't need to fill in the list by hand. We can automatize it using your yml files. I will spend some time on this later. It must be quick actually.

**Comment by orelgueta** [comment]
Don't work on it, I already have a list with type per parameter. The problem there is that special parameters with a list of floats are listed just as a float, so I never used it (I don't have a use case for it).
What I suggest is to keep this information in the DB. If we only make a list of special parameters (like nightsky_background), then I can save the values in the yaml DB with their correct type (float/int/string). This way, you don't need to cast any of them later. 
I will save them this way also in the MongoDB DB, perhaps with the type in an explicit field, not sure yet.

I don't need a specific parameter now, so don't worry about it. (Well, the effective focal length, but I simply cast it explicitly in the camera class at the moment.)

**Comment by RaulRPrado** [comment]
Ok.

You mean, from a Camera class, you will get a parameter from the TelescopeModel?
This is very different from what I was planning for the sub model classes. We should discuss the design of these modules before implementing it.

**Comment by orelgueta** [comment]
Yes, I made a note to myself to discuss this class/application with you. I know you had a specific vision on how to transfer such information. I will open a specific issue with a reference to the code before I do the pull request (it's already implemented and working, but it's not a big deal to change).

**Comment by RaulRPrado** [comment]
Ok, good =)

**Comment by orelgueta** [comment]
I guess this is solved already now that the DB has the correct data types. Can I close this?

**Comment by RaulRPrado** [comment]
Sure
