### ISSUE TITLE
derive_rnda_mirror_angle reads the DB for each mirror

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#187]
As discussed in #176, derive_rnda_mirror_angle could read the DB only once.

**Comment by RaulRPrado** [comment]
I had a look at the application and it turns out that we read the DB only once. See:

https://github.com/gammasim/gammasim-tools/blob/3990ca55098da48d59d8aec083071eb86532ebc2/applications/derive_mirror_rnda.py#L219-L224

For every mirror and new value of rnda_mirror_angle, we only replace the parameters using the same instance of TelecopeModel.

If there is a problem with the DB connection being open for too long, we could consider a public function in DatabaseHandler to close the connection.

**Comment by orelgueta** [comment]
That is true in the application itself. However, every time we make the run command we call the getConfigFile()

https://github.com/gammasim/gammasim-tools/blob/3990ca55098da48d59d8aec083071eb86532ebc2/simtools/simtel/simtel_runner_ray_tracing.py#L186

that in turn exports the config file if it is updated (which I assume it is for each mirror)

https://github.com/gammasim/gammasim-tools/blob/3990ca55098da48d59d8aec083071eb86532ebc2/simtools/model/telescope_model.py#L510-L525

and that calls the DB

https://github.com/gammasim/gammasim-tools/blob/3990ca55098da48d59d8aec083071eb86532ebc2/simtools/model/telescope_model.py#L486-L496

I am fairly certain we are reading from the DB constantly because if I look at the number of operations per-second while running this application I get the plot below

![image](https://user-images.githubusercontent.com/22728856/154442708-124d73cc-af04-49da-b04c-c94874594eae.png)

**Comment by RaulRPrado** [comment]
Ok, that is quite nested.
We connect again to the DB to export the model files, not to read the parameters.

I have then to split the self._isConfigFileUpdated flag into two: one for the model files and another for the parameters.

**Comment by orelgueta** [comment]
Why do we need to export the model files again for each run?

**Comment by RaulRPrado** [comment]
> Why do we need to export the model files again for each run?

I don't, that is the problem. I only need to export if any parameter that isFile was changed/added.

**Comment by orelgueta** [comment]
Ahh OK, now I see what you mean.

**Comment by RaulRPrado** [comment]
Fixed by #193
