### ISSUE TITLE
Reading of contents of camera_config_file from database

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#234]
We read the name of the camera_config_file from the model DB in ./applications/validate_camera_fov.py, but not the content of the file (which I think is as well in the DB). We probably want to either

- read both name and contents of the file from the model database
- read a user-defined file (through configuration parameters) from disk.

Right now we are mixing both.

This is relevant e.g., here:

https://github.com/gammasim/gammasim-tools/blob/f95ea3c4a6b4170bdd08c46ca5b725dc91bfead1/applications/validate_camera_fov.py#L106

**Comment by orelgueta** [comment]
This was fixed already in #347 and in particular in [e1e9dd4](https://github.com/gammasim/gammasim-tools/commit/e1e9dd4e405f29a1985bdf67dc8e4470c801afca). I didn't even notice this issue was about that. At the time I simply realised that it was silly that we redefined the camera model explicitly instead of just taking the one from the telescope model.
