### ISSUE TITLE
config file structure

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#24]
This looks a bit cumbersome, would it be easier to define one single CTA model directory and then assume the svn directory structure?

https://github.com/gammasim/gammasim-tools/blob/9a7dda195b348d66788ce94b1408497d147b4f7a/config.yml#L6

**Comment by RaulRPrado** [comment]
I don't think it's cumbersome. It's only few directories listed. Ideally only 3 actually, we listed more for the sake of convenience while developing.

These files are yaml files created by Orel, data model files in the sim_telarray format and data files from instruments teams. They have different purposes and sources. They just happen to be all on svn and organized in this structure. So, it doesn't make sense to me constraining our framework to this specific structure that could and will change at some point.
One could, for example, decide to point to the sim_telarray cfg directory instead of the datFiles from svn. 

BTW, some of these files will be covered later by a DB.

**Comment by GernotMaier** [comment]
Exactly - because it is temporary it should be as simple as possible, but it is only a minor point and we can leave it as simple as possible. All the hardcoded paths are just not elegant and changing 3 (actually 5) lines instead of 1 is not ideal. Minor - closing it therefore.

**Comment by RaulRPrado** [comment]
> Exactly - because it is temporary it should be as simple as possible, but it is only a minor point and we can leave it as simple as possible. All the hardcoded paths are just not elegant and changing 3 (actually 5) lines instead of 1 is not ideal. Minor - closing it therefore.

You are not suppose to "change" lines, you are suppose to set your own config file. The idea of the config file is exactly **not** to hardcode these paths. 
You can keep all the model files in the same directory and give only one path, if you want. The code doesn't discriminate between all the directories listed, it just search a certain file in all of them. It's the simplest solution to me. I don't think that requiring the user to organize his/her files in an arbitrary structure is a better option.

**Comment by orelgueta** [comment]
Can we make the sim_telarray location into a list like the modelFilesLocations? Either that, or simply not track the config.yml on github so we can each have our own.

**Comment by RaulRPrado** [comment]
Sure. I'll do that in the develop branch later today

**Comment by RaulRPrado** [comment]
Well, actually I replied without giving it to much thought.
I think making it a list is not a good idea. Maybe we could mv config.yml to config_template.yml. Then we track config_template on git and each of us keep a config.yml locally which is not tracked.
Does that work?

**Comment by orelgueta** [comment]
Sure, that's fine with me. 
I also wrote this before the sim_telarray installation failed on my laptop, so I am not sure how useful it will be in the end, but probably a good idea anyway.

**Comment by RaulRPrado** [comment]
Great. Can you do that at the develop branch?

**Comment by orelgueta** [comment]
Sure, I will do that.
