### ISSUE TITLE
Layout plotting (sites branch)

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#339]
Integrate plotting of telescope layouts.

- [ ] sites branch integration
- [ ] check and possible use plotting from ctapipe or ctaplot

**Comment by VictorBarbosaMartins** [comment]
Hi Gernot. Could I integrate this into the atmosphere tool issue and work on it? It is slightly related to the production of a large array of telescopes that I'm working on. I've been looking into the code and I haven't found a plotting application for the array yet, only the printing of array position. Is that right or have I missed something?

**Comment by GernotMaier** [comment]
Probably won't want to mix it with the atmosphere tool, but this is still something to do. @orelgueta , can you comment on the plotting?

**Comment by orelgueta** [comment]
There are simple plotting tools in the sites branch already. Just need to decide if we want them and if we do, where to add them (in visualize or in layout class).

Another option is to use this opportunity and import the array plotting from ctapipe (though it doesn't really fit our needs exactly since we want the telescope numbers and stuff)
