### ISSUE TITLE
kwargs usage

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#34]
https://github.com/gammasim/gammasim-tools/blob/102c47e4a559094a76f554929883813b0f5dbab4/simtools/model/telescope_model.py#L268

For some reason, Github doesn't allow me to comment on code that was not included in the PR commits, so I have to open a new issue for this...
Anyway, isn't this abusing the kwargs keyword? You are simply passing a normal dict, why not give it a meaningful name and pass a normal dict object? This happens in other places in this file as well (not sure if in others).

**Comment by RaulRPrado** [comment]
No, this is exactly how kwargs are suppose to be used. **kwargs is not the same as a dict.
You can expand a dict with ** and pass it as kwargs, but it is different than receiving a dict as argument.

If you mean that we should just use a different word, like **parameters, yes, we could, but I think the kwargs keyword is fine in this case. For the user it's only important to know that the function receive kwargs. And for implementation, it's always clear what the kwargs mean.
I think it's actually better for readability to keep the name kwargs because its function is always clear. Otherwise the developer will have to think twice to understand that that argument is a kwarg.

**Comment by orelgueta** [comment]
Oh, sorry, I misunderstood the goal of the function. I thought you always receive a dict, but in this case you allow also to list parameters explicitly. Forget about it, I will close the issue.
