### ISSUE TITLE
telescope_modell:isAstri - true for all SSTs?

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#359]
https://github.com/gammasim/gammasim-tools/blob/67fd2e3e6d347e415b42e1dcb029501a996388c9/simtools/model/telescope_model.py#L724

Isn't that true also for a telescope type name 'SST'?, 'SST-D' is probably not an ASTRI telescope?

Do we actually need this function, it is used here: https://github.com/gammasim/gammasim-tools/blob/67fd2e3e6d347e415b42e1dcb029501a996388c9/simtools/camera_efficiency.py#L220

-> why would testeff work for 2D tables of other telescopes types? Isn't it enough to check here for a 2D table only?

**Comment by orelgueta** [comment]
I am working on this function these days as part of #128, so I suggest to close this issue as a duplication. The ASTRI part is because the 1D table is hardcoded there and Raul wanted to make sure we use the correct value (in this case there's no difference between ASTRI and SST-D). After I finish with my PR, we won't need this function anymore.
