### ISSUE TITLE
Adapt the telescope names for the MongoDB style

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#49]

**Comment by RaulRPrado** [comment]
@orelgueta , do we want to keep the old names (e.g. SST-2M-GCT-S) as possibilities, or they don't make sense with the MongoDB?

**Comment by orelgueta** [comment]
Great question...
My gut instinct says we should keep those names for backward compatibility. On the other hand, I do not have those names in  MongoDB and we don't expect to use them in the future...
If you remove them then we won't be able to simulate those telescopes anymore right? That might be a bit of a problem I guess.
@GernotMaier, what do you think?

**Comment by GernotMaier** [comment]
It would of course be nice to keep to add the prod3/prod4 models to the DB - this means to use these names? What is the problem with that?

**Comment by orelgueta** [comment]
They don't fit the new naming scheme we have. So, either we have to keep both options (which could be annoying to code), or we come up with new names that fit the scheme (like South-GCT-D). The titles can still be kept as is of course. Raul will comment on how much extra work that introduces (for me it's not too bad).

**Comment by RaulRPrado** [comment]
Creating the new names seems the best option, assuming it is not a lot of work from the DB side.
To be consistent, we should use "South-SST-GCT", "South-SST-ASTRI" and "South-SST-1M".

**Comment by orelgueta** [comment]
Sure. For me it's not a big deal. We might want to keep the old titles though, they were, at some point, selected as "official" titles. Whatever that means.

**Comment by RaulRPrado** [comment]
Ok, perfect.

What titles? For the plots?

**Comment by orelgueta** [comment]
Yes, but also everywhere else the telescope is referred to. Other than the title of each report, the telescopes are mentioned in the text with their titles rather than their names. For example, "MST Structure" rather than "MST-optics".
We will probably have to change this dictionary 

https://github.com/gammasim/gammasim-tools/blob/63dac4db59fe69b9ae8adfdcde21b347b8ab2c9d/simtools/util/names.py#L73

to a yaml file which will provide a few more options like in

https://gitlab.cta-observatory.org/cta-consortium/aswg/simulations/simulation-model/simulation-model-description/-/blob/master/configReports/telescopesInfo.yml#L49

but we can deal with it later, when I integrate the reports further into gammasim.

**Comment by RaulRPrado** [comment]
Ok. We can write converters to go from the DB name to these titles.

**Comment by RaulRPrado** [comment]
Done by the tel-names PRs (https://github.com/gammasim/gammasim-tools/commit/3a799d105a719bc53e3fb90b5b33c31ee567673f)
