### ISSUE TITLE
Sim-telarray and corsika

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#74]
From the sim_telarray package:

- do we need only the exectutables in sim_telarray/bin/ or any other file?

For those applications which rely on CORSIKA only (so don't need sim_telarray): do need the CORSIKA as provided in the sim_telarray package, or can we use e.g., the corsika package as distributed by KIT?

**Comment by RaulRPrado** [comment]
We still need the simtel directory because of some cfg files. This will change soon when I start pointing simtel to our local directory with the cfg files created from the DB.

About CORSIKA: there is still no application that uses CORSIKA at all, by the moment. So I never actually thought about it.
I honestly don't see any reason to allow for a standalone CORSIKA distribution. Yes, there will be (few) applications that uses only CORSIKA, and not simtel. However, which kind of user would be interested only on these applications?
I wouldn't spend any time on this so soon, for the sake of time optimization.

**Comment by GernotMaier** [comment]
OK - just wanted to make sure that we have thought about this.
