### ISSUE TITLE
Missing file error (not actually missing?)

### ISSUE THREAD

**Issue by orelgueta** [gammasim/gammasim-tools#89]
When running derive_mirror_rnda.py I see the error 

> ERROR::config(l196)::findFile::File mirror_MST_focal_lengths.dat could not be found in /afs/ifh.de/group/cta/scratch/ogueta/cta/gammasim/gammasim-tools/simtools-output/derive_mirror_rnda/model

However, the application continues without issues. My guess is that "findFile" reports an error after searching in the first location in "config.yml", but before finding the file in the second location. Could that be true? If so, should probably fix.

**Comment by RaulRPrado** [comment]
The problem is at the telescope_model, where we try to find it at the application config directory and, if not, we search it at the modelFilesLocation from the config file. See below. 

`try:
     mirrorListFile = cfg.findFile(mirrorListFileName, self._configFileDirectory)
except FileNotFoundError():
     mirrorListFile = cfg.findFile(mirrorListFileName, self._modelFilesLocations)`

I actually don't know what to do here. It's a real ERROR but it does not affect anything. Any idea?

One thing that I realize here is that we have to somehow copy the new model file to the application config directory. I will implement a function at the telescope_model called AddConfigFile and use it at the application level.

**Comment by RaulRPrado** [comment]
The error message from the findFile has to be printed. It is indeed an error that has to be prevented, even though it does not interrupt the flow.
I added a warning message right before to explain.

I added a function in the telescope_model to copy a parameter file to the local config directory. By using it in the application, we solve the error.

I consider this issue closed. @orelgueta?

**Comment by orelgueta** [comment]
So when running a full telescope simulation you will copy all config files to the application directory?

**Comment by RaulRPrado** [comment]
> So when running a full telescope simulation you will copy all config files to the application directory?

Yes, but this is already done by writing the files from the DB directly there. I just had to do it by hand because the mirror list in this case is not a regular file of the model. In the future we have to add all these files to the DB.

**Comment by orelgueta** [comment]
OK, sounds good. We can close this issue then.
