### ISSUE TITLE
Issue with local user when using MongoDB

### ISSUE THREAD

**Issue by RaulRPrado** [gammasim/gammasim-tools#92]
In my new laptop, my user is not the same one as in the DESY system.
When I try to connect to the DB, it asks me the password for wrong-user@warp.zeuthen.desy.de.

I fixed it here:
```
_tunnel = self._createTunnel(
            localport=self.dbDetails['localport'],
            remoteport=self.dbDetails['remoteport'],
            user=userDB,
            mongodbServer=self.dbDetails['mongodbServer'],
            tunnelServer=self.dbDetails['tunnelServer']
        )
```

Previously, the user here was taken from getpass.getuser(), and now I'm using the one from the DB config file.
@orelgueta  Is this a final solution? Why weren't we using userDB at first?

**Comment by orelgueta** [comment]
Wait, does the userDB work? It's not supposed to. I think Phillip set up just two users on the DB, "api" and my user with administrator privileges. Can you connect to the DB with your DESY username? 
Even if you can, you shouldn't. Everyone should use the "api" user which has limited privileges in order to avoid mistakes.

I didn't add a username for the tunnel at the time because when I set it up I asked both you and Gernot if your laptop's username is the same as the DESY one. We can add a user to one of the config files I guess, not sure what would be the best solution.

Either way, none of this is the final solution, we certainly hope this DB is a temporary one anyway.

**Comment by RaulRPrado** [comment]
But when you use getpass.getuser(), you are getting the local user, not "api", right?

> I didn't add a username for the tunnel at the time because when I set it up I asked both you and Gernot if your laptop's username is the same as the DESY one. We can add a user to one of the config files I guess, not sure what would be the best solution.

Ah ok.
Well, it used to be but not anymore. 
Another user to the dbDetails sounds the best for me. 

> Either way, none of this is the final solution, we certainly hope this DB is a temporary one anyway.

Yes, sure. "Final temporary solution" I meant =)

**Comment by orelgueta** [comment]
> But when you use getpass.getuser(), you are getting the local user, not "api", right?

Right, cause for the tunnel you need your local user (if it's the same as the DESY one). Only to access the DB itself you need "api" (which should be defined in dbDetails.yml). 

> Another user to the dbDetails sounds the best for me.

Sure, we can do that.

**Comment by orelgueta** [comment]
if #96 answers this issue, please close it.
