### ISSUE TITLE
File-not-found behaviour in validate_camera_efficiency.py

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#97]
When running

```
python applications/validate_camera_efficiency.py --tel_name South-SST-D
```

I get the following INFO / WARNING:

```
INFO::camera_efficiency(l319)::analyze::Spectrum weighted reflectivity: 0.9158008881525233
ERROR::config(l196)::findFile::File camera_CHEC-S_x9r.dat could not be found in /workdir/external/output/simtools-output/validate_camera_efficiency/model
WARNING::telescope_model(l534)::_loadCamera::CameraConfigFile was not found in the config directory - Using the one found in the modelFilesLocations
```

What does it mean and is it actually an ERROR? There is an expectation for camera_CHEC-S_x9r.dat  in a certain directory. As this is not found, it used some default. Does it mean it uses a default telescope model find in modelFilesLocations or that it found 'camera_CHEC-S_x9r.dat ' in modelFilesLocations?

**Comment by RaulRPrado** [comment]
This was discussed in another issue a while ago.

What happens now is that, when using the MongoDB, all the model files are written to this local directory. Then, when we need a file, we search for it on this local directory, and if not found, we search on the modelFilesLocation.

In this case, you were probably not using the MongoDB, so we didn't copy the files to the local model directory.

The question that I'm not sure about is whether or not this should be an error or just a warning.

We have to take into consideration that this behavior of searching in both directory is not suppose to be final one, since we will, at some point, remove the option of using yml files, and keep only the MongoDB option. So, in the final shape, this is actually an error. That is why I kept it like this.

One thing we can do at this point is also copying all the model files to the local directory, from the modelFilesLocation, whenever we build a model with yml files. This will logically fix this error. But on the other hand, the yml file option is only temporary.

**Comment by GernotMaier** [comment]
So maybe we should ignore that, as using the DB should be the default. 

I've switched now to the DB and it works without any problems.

I am closing this, ok?

**Comment by RaulRPrado** [comment]
Yes, ok.
